# Generated by Django 5.1.6 on 2025-04-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_addmovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmovie',
            name='userid',
        ),
    ]
